name: Chat App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: psql_user
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: chat_app

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create PostgreSQL User
        run: |
          sudo -u postgres createuser psql_user

      - name: Set Password for PostgreSQL User
        run: |
          sudo -u postgres psql -c "ALTER USER psql_user WITH PASSWORD 'postgres';"

      - name: Create Database
        run: |
          sudo -u postgres createdb chat_app

      - name: Create Schema
        run: |
          sudo -u postgres psql -d chat_app -c "CREATE SCHEMA chat;"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          export PYTHONPATH=$(pwd):$PYTHONPATH
          pytest